# Generated by Django 5.1.7 on 2026-03-03 13:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_instituicaofinanceira_categoria_estabelecimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandeira', models.CharField(blank=True, max_length=60, null=True)),
                ('cartao_final', models.CharField(max_length=8)),
                ('ativo', models.BooleanField(default=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='core.instituicaofinanceira')),
                ('membro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartoes', to='core.membro')),
            ],
        ),
        migrations.CreateModel(
            name='FaturaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechado_em', models.DateField()),
                ('vencimento_em', models.DateField()),
                ('competencia', models.DateField()),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('arquivo_hash', models.CharField(blank=True, max_length=40, null=True)),
                ('fonte_arquivo', models.CharField(blank=True, max_length=255, null=True)),
                ('import_batch', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='cartao_credito.cartao')),
            ],
        ),
        migrations.CreateModel(
            name='RegraMembroCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo_padrao', models.CharField(choices=[('exato', 'Texto exato'), ('contem', 'Contém o texto'), ('inicia_com', 'Inicia com'), ('termina_com', 'Termina com'), ('regex', 'Expressão regular')], default='contem', max_length=20)),
                ('padrao', models.CharField(max_length=200)),
                ('tipo_valor', models.CharField(choices=[('nenhum', 'Sem condição de valor'), ('igual', 'Igual a'), ('maior', 'Maior que'), ('menor', 'Menor que')], default='nenhum', max_length=10)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('prioridade', models.PositiveIntegerField(default=100, help_text='Quanto menor, mais cedo esta regra é avaliada.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('membros', models.ManyToManyField(blank=True, related_name='regras_membro_cartao', to='core.membro')),
            ],
            options={
                'verbose_name': 'Regra de Membro (Cartão)',
                'verbose_name_plural': 'Regras de Membro (Cartão)',
                'ordering': ('prioridade', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=80, null=True)),
                ('pais', models.CharField(blank=True, max_length=8, null=True)),
                ('secao', models.CharField(blank=True, max_length=40, null=True)),
                ('oculta', models.BooleanField(db_index=True, default=False)),
                ('oculta_manual', models.BooleanField(db_index=True, default=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moeda', models.CharField(blank=True, max_length=10, null=True)),
                ('valor_moeda', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('taxa_cambio', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('etiqueta_parcela', models.CharField(blank=True, max_length=20, null=True)),
                ('parcela_num', models.PositiveIntegerField(blank=True, null=True)),
                ('parcela_total', models.PositiveIntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('hash_linha', models.CharField(max_length=40)),
                ('hash_ordem', models.PositiveSmallIntegerField(default=1)),
                ('is_duplicado', models.BooleanField(default=False)),
                ('fitid', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='core.categoria')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='cartao_credito.faturacartao')),
                ('membros', models.ManyToManyField(blank=True, related_name='transacoes_cartao', to='core.membro')),
            ],
        ),
        migrations.AddIndex(
            model_name='cartao',
            index=models.Index(fields=['cartao_final'], name='cartao_cred_cartao__20dfe5_idx'),
        ),
        migrations.AddIndex(
            model_name='cartao',
            index=models.Index(fields=['membro'], name='cartao_cred_membro__1a7a65_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartao',
            constraint=models.UniqueConstraint(fields=('instituicao', 'bandeira', 'cartao_final'), name='uniq_cartao_instituicao_bandeira_final'),
        ),
        migrations.AddIndex(
            model_name='faturacartao',
            index=models.Index(fields=['competencia', 'cartao'], name='cartao_cred_compete_a95e29_idx'),
        ),
        migrations.AddIndex(
            model_name='faturacartao',
            index=models.Index(fields=['fechado_em'], name='cartao_cred_fechado_d92ab3_idx'),
        ),
        migrations.AddConstraint(
            model_name='faturacartao',
            constraint=models.UniqueConstraint(fields=('cartao', 'competencia'), name='uniq_fatura_por_cartao_competencia'),
        ),
        migrations.AddIndex(
            model_name='regramembrocartao',
            index=models.Index(fields=['ativo', 'prioridade'], name='cartao_cred_ativo_ee18ca_idx'),
        ),
        migrations.AddIndex(
            model_name='transacao',
            index=models.Index(fields=['fatura', 'data'], name='cartao_cred_fatura__50765a_idx'),
        ),
        migrations.AddConstraint(
            model_name='transacao',
            constraint=models.UniqueConstraint(fields=('fatura', 'hash_linha', 'hash_ordem'), name='uniq_lcto_por_fatura_hash_ordem'),
        ),
    ]
