# Generated by Django 5.1.7 on 2026-03-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_credito', '0002_invert_transacao_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='anotacao',
            field=models.CharField(blank=True, help_text='Comentário ou identificação manual da transação.', max_length=255, null=True),
        ),
    ]
