# Generated by Django 5.1.7 on 2026-03-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_credito', '0003_create_transacao_if_missing'),
        ('cartao_credito', '0003_transacao_anotacao'),
    ]

    operations = [
    ]
