version: "3.8"

services:
  hsmoney:
    image: dalhisa/hsmoney:latest
    environment:
      SECRET_KEY: ${SECRET_KEY:?Defina SECRET_KEY}
      DEBUG: ${DEBUG:-False}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-*}
      DB_NAME: ${DB_NAME:-hsmoney_db}
      DB_USER: ${DB_USER:-hsmoney}
      DB_PASSWORD: ${DB_PASSWORD:?Defina DB_PASSWORD}
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "8001:8000"   # evita conflito com Portainer
    networks:
      - db_stack_default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  db_stack_default:
    external: true