version: "3.8"

services:
  hsmoney:
    image: dalhisa/hsmoney:latest
    environment:
      SECRET_KEY: ${SECRET_KEY:?Defina SECRET_KEY}
      DEBUG: ${DEBUG:-False}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-*}
      DB_NAME: hsmoney_db
      DB_USER: admin
      DB_PASSWORD: ${DB_PASSWORD:?Defina DB_PASSWORD}
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "8001:8000"   # evita conflito com Portainer
    networks:
      - db_stack_default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn hs_money.wsgi:application --bind 0.0.0.0:8000"

networks:
  db_stack_default:
    external: true