# Generated by Django 5.1.7 on 2026-03-03 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_instituicaofinanceira_categoria_estabelecimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaCorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Agência')),
                ('numero', models.CharField(max_length=30, verbose_name='Número')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_correntes', to='core.instituicaofinanceira')),
                ('membro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_correntes', to='core.membro')),
            ],
            options={
                'verbose_name': 'Conta Corrente',
                'verbose_name_plural': 'Contas Correntes',
            },
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Início')),
                ('data_fim', models.DateField(verbose_name='Fim')),
                ('arquivo_hash', models.CharField(blank=True, max_length=40, null=True)),
                ('fonte_arquivo', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extratos', to='conta_corrente.contacorrente')),
            ],
            options={
                'verbose_name': 'Extrato',
                'verbose_name_plural': 'Extratos',
                'ordering': ['-data_fim'],
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('hash_linha', models.CharField(max_length=40)),
                ('hash_ordem', models.PositiveSmallIntegerField(default=1)),
                ('is_duplicado', models.BooleanField(default=False)),
                ('fitid', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_cc', to='core.categoria')),
                ('extrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='conta_corrente.extrato')),
                ('membros', models.ManyToManyField(blank=True, related_name='transacoes_cc', to='core.membro')),
            ],
            options={
                'verbose_name': 'Transação CC',
                'verbose_name_plural': 'Transações CC',
            },
        ),
        migrations.AddConstraint(
            model_name='contacorrente',
            constraint=models.UniqueConstraint(fields=('instituicao', 'agencia', 'numero'), name='uniq_conta_inst_agencia_numero'),
        ),
        migrations.AddIndex(
            model_name='transacao',
            index=models.Index(fields=['extrato', 'data'], name='conta_corre_extrato_5603b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='transacao',
            constraint=models.UniqueConstraint(fields=('extrato', 'hash_linha', 'hash_ordem'), name='uniq_lcto_cc_hash_ordem'),
        ),
    ]
