# Generated by Django 5.1.7 on 2026-03-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta_corrente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo'),
        ),
    ]
