# Generated by Django 5.2.11 on 2026-03-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta_corrente', '0002_add_tipo_to_transacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='oculta',
            field=models.BooleanField(default=False, verbose_name='Oculta'),
        ),
    ]
