# Generated by Django 5.2.11 on 2026-03-03 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta_corrente', '0003_add_oculta_to_transacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name': 'Transação', 'verbose_name_plural': 'Transações'},
        ),
    ]
