# Generated by Django 5.1.7 on 2026-03-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta_corrente', '0004_alter_transacao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='anotacao',
            field=models.CharField(blank=True, help_text='Comentário ou identificação manual da transação.', max_length=255, null=True, verbose_name='Anotação'),
        ),
    ]
