# Generated by Django 5.1.7 on 2026-03-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0004_patrimonioinvestimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentoplanejado',
            name='dia_da_semana',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], help_text='Dia da semana para recorrência semanal (0=Segunda … 6=Domingo)', null=True, verbose_name='Dia da semana'),
        ),
        migrations.AlterField(
            model_name='lancamentoplanejado',
            name='periodicidade',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual'), ('semanal', 'Semanal')], default='mensal', max_length=10, verbose_name='Periodicidade'),
        ),
    ]
