# Generated by Django 5.2.11 on 2026-03-10 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_add_ordem_to_membro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('FUNDO_RF', 'Fundo Renda Fixa'), ('FUNDO_RV', 'Fundo Renda Variável'), ('TESOURO', 'Tesouro Direto'), ('ACAO', 'Ação'), ('OUTRO', 'Outro')], default='FUNDO_RF', max_length=20, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investimentos', to='core.instituicaofinanceira')),
                ('membro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investimentos', to='core.membro')),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
                'ordering': ['membro', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo', models.CharField(choices=[('APL', 'Aplicação'), ('RES', 'Resgate')], max_length=3, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor')),
                ('descricao', models.CharField(blank=True, default='', max_length=255, verbose_name='Descrição')),
                ('anotacao', models.CharField(blank=True, help_text='Comentário ou identificação manual.', max_length=255, null=True, verbose_name='Anotação')),
                ('investimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='investimentos.investimento')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='SaldoInvestimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data de referência')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Saldo')),
                ('investimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='investimentos.investimento')),
            ],
            options={
                'verbose_name': 'Saldo de Investimento',
                'verbose_name_plural': 'Saldos de Investimentos',
                'ordering': ['-data'],
            },
        ),
        migrations.AddConstraint(
            model_name='investimento',
            constraint=models.UniqueConstraint(fields=('instituicao', 'membro', 'nome'), name='uniq_invest_inst_membro_nome'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['investimento', 'data'], name='investiment_investi_c7aef6_idx'),
        ),
        migrations.AddConstraint(
            model_name='saldoinvestimento',
            constraint=models.UniqueConstraint(fields=('investimento', 'data'), name='uniq_saldo_invest_data'),
        ),
    ]
