# Generated by Django 5.1.7 on 2026-03-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0002_add_tipo_financeiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='projecao_adicional',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor somado ao saldo todo mês. Use negativo para resgates fixos.', max_digits=14, null=True, verbose_name='Ajuste fixo mensal (R$)'),
        ),
        migrations.AddField(
            model_name='investimento',
            name='projecao_percentual',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Ex: 1.5 para crescer 1,5% ao mês.', max_digits=8, null=True, verbose_name='Variação mensal (%)'),
        ),
    ]
