# Generated by Django 5.1.7 on 2026-03-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0003_add_projecao_to_investimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investimento',
            name='projecao_adicional',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Somado ao saldo todo mês. Negativo = resgata; positivo = aporta.', max_digits=14, null=True, verbose_name='Ajuste fixo mensal (R$)'),
        ),
    ]
