# Generated by Django 5.2.11 on 2026-02-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('adulto', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-adulto', 'nome'],
            },
        ),
        migrations.DeleteModel(
            name='Example',
        ),
    ]
