# Generated by Django 5.1.7 on 2026-02-20 15:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membro_delete_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituicaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(choices=[('banco', 'Banco'), ('corretora', 'Corretora'), ('fintech', 'Fintech'), ('cooperativa', 'Cooperativa'), ('outro', 'Outro')], default='banco', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.PositiveSmallIntegerField(choices=[(1, 'Macro'), (2, 'Sub')], default=1)),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='core.categoria')),
            ],
            options={
                'ordering': ['nivel', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=200, unique=True)),
                ('categoria_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estabelecimentos', to='core.categoria')),
            ],
            options={
                'ordering': ['nome_fantasia'],
            },
        ),
        migrations.CreateModel(
            name='AliasEstabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_alias', models.CharField(max_length=200)),
                ('nome_base', models.CharField(blank=True, db_index=True, default='', help_text='Forma normalizada do alias para agrupar variações (preenchido automaticamente).', max_length=200)),
                ('mestre', models.ForeignKey(blank=True, help_text='Alias principal ao qual esta variante pertence (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variantes', to='core.aliasestabelecimento')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.estabelecimento')),
            ],
            options={
                'ordering': ['nome_base', 'nome_alias'],
            },
        ),
        migrations.CreateModel(
            name='RegraAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padrao_regex', models.CharField(help_text="Regex aplicada sobre o texto normalizado (ex.: r'\\bAMAZON\\b|\\bAMAZON MARKET\\b')", max_length=255)),
                ('prioridade', models.PositiveIntegerField(default=100, help_text='Menor número = regra aplicada primeiro.', validators=[django.core.validators.MinValueValidator(1)])),
                ('ativo', models.BooleanField(default=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_alias', to='core.estabelecimento')),
            ],
            options={
                'ordering': ['prioridade', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RegraCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, default='', max_length=140)),
                ('padrao_regex', models.CharField(help_text='Regex aplicada sobre o texto normalizado (alias_base/descrição).', max_length=255)),
                ('prioridade', models.PositiveIntegerField(default=100, help_text='Menor número = regra aplicada primeiro.', validators=[django.core.validators.MinValueValidator(1)])),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_categoria', to='core.categoria')),
            ],
            options={
                'ordering': ['prioridade', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('categoria_pai', 'nome'), name='uix_categoria_pai_nome'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('categoria_pai__isnull', True), ('nivel', 1)), models.Q(('categoria_pai__isnull', False), ('nivel', 2)), _connector='OR'), name='chk_categoria_nivel_vs_pai'),
        ),
        migrations.AddConstraint(
            model_name='aliasestabelecimento',
            constraint=models.UniqueConstraint(fields=('estabelecimento', 'nome_alias'), name='uix_estabelecimento_nome_alias'),
        ),
    ]
