# Generated by Django 5.2.11 on 2026-03-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_instituicaofinanceira_categoria_estabelecimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nivel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Categoria'), (2, 'Subcategoria')], default=1),
        ),
    ]
